language: python
python:
  - 3.6
install:
  - pip install pipenv
  - pipenv install -d --system
script:
  - ./manage.py collectstatic
  - coverage run --source='./onlinejudge' manage.py test
  - coverage report
after_success: coveralls